# Site settings
title: Statistical Genetics journal club
tag_text: Statistical Genetics journal club
description: The website for the Statistical Genetics journal club based at the University of Melbourne.

# Build settings
markdown: kramdown
exclude: ["README.md", "Gemfile"]
sass:
  style: compressed
